### ISSUE TITLE
wskey自动禁用

### ISSUE THREAD

**Issue by SliverGod** [Zy143L/wskey#104]
日志报错：
`pt_pin=jd_7885c98767d8a;检索成功

--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1085, in emit
    msg = self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 929, in format
    return fmt.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 668, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.8/logging/__init__.py", line 373, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "Zy143L_wskey_wskey.py", line 440, in <module>
    if not check_ck(jck):  # bool: False 判定 JD_COOKIE 有效性
  File "Zy143L_wskey_wskey.py", line 157, in check_ck
    logger.info("JD接口错误码: ", res.status_code)
Message: 'JD接口错误码: '
Arguments: (401,)
pin=jd_7885c98767d8a;WsKey状态正常

wskey转换成功

账号启用`

**90%账号运行时，日志会报错。**
而且，不知道触发了什么，会自动禁用部分JD_WSCK，手动开启后，转换成ck可正常跑脚本，麻烦懂哥解惑，感激不尽

**Comment by Zy143L** [comment]
稍后解决

**Comment by Zy143L** [comment]
请更新脚本
