### ISSUE TITLE
抓取的wskey无法使用，程序直接崩溃

### ISSUE THREAD

**Issue by kolicime** [Zy143L/wskey#112]
在同一台设备上抓取的wskey，前几个号还是好的，第5个号开始，抓取的wskey放到环境变量里一跑程序就崩溃。前几个wskey还是正常的
把会出问题的wskey放在最前面
```
--------------------

5700端口检查通过

当前脚本版本: 1118
--------------------

Verification passed
--------------------

pt_pin=jd_xxxxx;检索成功

企业微信应用 推送打开
企业微信机器人 推送打开
Traceback (most recent call last):
  File "Zy143L_wskey_wskey.py", line 132, in check_ck
    res = requests.get(url=url, headers=headers, verify=False, timeout=10)
  File "/usr/lib/python3.8/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 456, in prepare_request
    p.prepare(
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 317, in prepare
    self.prepare_headers(headers)
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 451, in prepare_headers
    check_header_validity(header)
  File "/usr/lib/python3.8/site-packages/requests/utils.py", line 978, in check_header_validity
    raise InvalidHeader("Invalid return character or leading space in header: %s" % name)
requests.exceptions.InvalidHeader: Invalid return character or leading space in header: Cookie

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Zy143L_wskey_wskey.py", line 448, in <module>
    if not check_ck(jck):  # bool: False 判定 JD_COOKIE 有效性
  File "Zy143L_wskey_wskey.py", line 141, in check_ck
    res = requests.get(url=url, headers=headers, verify=False, timeout=30)
  File "/usr/lib/python3.8/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 456, in prepare_request
    p.prepare(
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 317, in prepare
    self.prepare_headers(headers)
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 451, in prepare_headers
    check_header_validity(header)
  File "/usr/lib/python3.8/site-packages/requests/utils.py", line 978, in check_header_validity
    raise InvalidHeader("Invalid return character or leading space in header: %s" % name)
requests.exceptions.InvalidHeader: Invalid return character or leading space in header: Cookie
```
把正常的wskey放在前面
```
--------------------

5700端口检查通过

当前脚本版本: 1118
--------------------

Verification passed
--------------------

pt_pin=80716357-403369;检索成功

 pt_pin=80716357-403369;状态正常

pt_pin=80716357-403369;账号有效

账号启用
--------------------

--------------------

pt_pin=jd_59cdf2f3931b9;检索成功

 pt_pin=jd_59cdf2f3931b9;状态正常

pt_pin=jd_59cdf2f3931b9;账号有效

账号启用
--------------------

--------------------

pt_pin=jd_4ac3b0e48a675;检索成功

 pt_pin=jd_4ac3b0e48a675;状态正常

pt_pin=jd_4ac3b0e48a675;账号有效

账号启用
--------------------

--------------------

pt_pin=jd_5157c54b031e9;检索成功

 pt_pin=jd_5157c54b031e9;状态正常

pt_pin=jd_5157c54b031e9;账号有效

账号启用
--------------------

--------------------

pt_pin=jd_5098cc8f4765f;检索成功

 pt_pin=jd_5098cc8f4765f;状态正常

pt_pin=jd_5098cc8f4765f;账号有效

账号启用
--------------------

--------------------

pt_pin=jd_vpIACxyFpMAs;检索成功

企业微信应用 推送打开
企业微信机器人 推送打开
Traceback (most recent call last):
  File "Zy143L_wskey_wskey.py", line 132, in check_ck
    res = requests.get(url=url, headers=headers, verify=False, timeout=10)
  File "/usr/lib/python3.8/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 456, in prepare_request
    p.prepare(
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 317, in prepare
    self.prepare_headers(headers)
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 451, in prepare_headers
    check_header_validity(header)
  File "/usr/lib/python3.8/site-packages/requests/utils.py", line 978, in check_header_validity
    raise InvalidHeader("Invalid return character or leading space in header: %s" % name)
requests.exceptions.InvalidHeader: Invalid return character or leading space in header: Cookie

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Zy143L_wskey_wskey.py", line 448, in <module>
    if not check_ck(jck):  # bool: False 判定 JD_COOKIE 有效性
  File "Zy143L_wskey_wskey.py", line 141, in check_ck
    res = requests.get(url=url, headers=headers, verify=False, timeout=30)
  File "/usr/lib/python3.8/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 456, in prepare_request
    p.prepare(
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 317, in prepare
    self.prepare_headers(headers)
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 451, in prepare_headers
    check_header_validity(header)
  File "/usr/lib/python3.8/site-packages/requests/utils.py", line 978, in check_header_validity
    raise InvalidHeader("Invalid return character or leading space in header: %s" % name)
requests.exceptions.InvalidHeader: Invalid return character or leading space in header: Cookie
```

**Comment by lostme01** [comment]
我也遇到了，有一个分号是中文的！你看看你的是不是？

**Comment by Zy143L** [comment]
检查空格 中文分号等问题

**Comment by kolicime** [comment]
并没有中文分号。刚刚又去试了一下居然神奇的正常了，而且我没有更新过脚本也没修改过wsck。。感觉是玄学问题
