### ISSUE TITLE
更新ck的时候报错

### ISSUE THREAD

**Issue by lostme01** [Zy143L/wskey#115]
Traceback (most recent call last):
  File "wskey.py", line 445, in <module>
    return_serch = serch_ck(wspin)  # 变量 pt_pin 搜索获取 key eid
  File "wskey.py", line 327, in serch_ck
    conn.request("GET", url, payload, headers)
  File "/usr/lib/python3.8/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1263, in _send_request
    self.putrequest(method, url, **skips)
  File "/usr/lib/python3.8/http/client.py", line 1101, in putrequest
    self._output(self._encode_request(request))
  File "/usr/lib/python3.8/http/client.py", line 1181, in _encode_request
    return request.encode('ascii')
UnicodeEncodeError: 'ascii' codec can't encode character '\uff1b' in position 49: ordinal not in range(128)

## 执行结束... 2021-11-29 18:25:16 耗

**Comment by lostme01** [comment]
找到问题了，pin 后面的分号是中文的！
