### ISSUE TITLE
更新后出现问题

### ISSUE THREAD

**Issue by RavenousHydra1** [Zy143L/wskey#168]
Traceback (most recent call last):
  File "wskey.py", line 549, in <module>
    return_serch = serch_ck(wspin)  # 变量 pt_pin 搜索获取 key eid
  File "wskey.py", line 383, in serch_ck
    updatedAt = envlist[i]['updatedAt']
KeyError: 'updatedAt'

**Comment by Zy143L** [comment]
从新更新 合并了有问题的代码
