### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by yuanxy** [Zy143L/wskey#213]
5700端口检查通过
Traceback (most recent call last):
  File "/ql/data/scripts/Zy143L_wskey/wskey.py", line 456, in <module>
    ql_id = check_id()  # 调用方法 [check_id] 并赋值 [ql_id]
  File "/ql/data/scripts/Zy143L_wskey/wskey.py", line 326, in check_id
    if '_id' in res['data'][0]:  # 判断 [_id]
IndexError: list index out of range

**Comment by Zy143L** [comment]
是否为全新青龙  env无配置的?

**Comment by HimeHome** [comment]
因为脚本异常死循环导致频繁请求1.117.193.*** 麻烦去除一下谢谢

**Comment by yuanxy** [comment]
我新增 ck 配置后 好了，应该是 读取 ck 系统参数那里有问题。
