### ISSUE TITLE
最新青龙2.13.2报错

### ISSUE THREAD

**Issue by Wangsc1** [Zy143L/wskey#238]
## 开始执行... 2022-06-01 13:01:35

--------------------

5600端口检查通过
Traceback (most recent call last):
  File "/ql/data/scripts/Zy143L_wskey/wskey.py", line 575, in <module>
    ql_id = check_id()  # 调用方法 [check_id] 并赋值 [ql_id]
  File "/ql/data/scripts/Zy143L_wskey/wskey.py", line 447, in check_id
    if '_id' in res['data'][0]:  # 判断 [_id]
IndexError: list index out of range

## 执行结束... 2022-06-01 13:01:35 耗时 0 秒

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by Zy143L** [comment]
5600端口是你自己改的么

**Comment by Wangsc1** [comment]
是的，我一直都是用的5600

**Comment by Zy143L** [comment]
你是第一次跑脚本 还是 这就这次出问题了?

**Comment by Wangsc1** [comment]
之前老版本的青龙一直用没问题，今天vps重装系统装完最新的青龙一跑就这样

**Comment by Zy143L** [comment]
试试改成5700再跑 或者删掉自定义端口

**Comment by Zy143L** [comment]
如果还是有问题 你开debug模式 .. 难道是青龙又换字段了??

**Comment by Wangsc1** [comment]
-p 5700:5700 \ 还是一样，debug咋开😂

**Comment by Wangsc1** [comment]
## 开始执行... 2022-06-01 13:47:49


DEBUG模式开启!


--------------------

5700端口检查通过
'twoFactorSecret'
Starting new HTTP connection (1): 127.0.0.1:5700
http://127.0.0.1:5700 "GET /api/user HTTP/1.1" 200 None
Starting new HTTP connection (1): 127.0.0.1:5700
http://127.0.0.1:5700 "GET /api/envs HTTP/1.1" 200 None
Traceback (most recent call last):
  File "/ql/data/scripts/Zy143L_wskey/wskey.py", line 575, in <module>
    ql_id = check_id()  # 调用方法 [check_id] 并赋值 [ql_id]
  File "/ql/data/scripts/Zy143L_wskey/wskey.py", line 447, in check_id
    if '_id' in res['data'][0]:  # 判断 [_id]
IndexError: list index out of range

## 执行结束... 2022-06-01 13:47:49 耗时 0 秒

**Comment by Zy143L** [comment]
话说你青龙的/env 环境里面 有写东西吗

**Comment by Wangsc1** [comment]
没有，随便填了个JD_COOKIE再跑就好了😂，打扰了

**Comment by Zy143L** [comment]
....啊这 你啥变量都没写 就开始跑脚本? 🤯

**Comment by Wangsc1** [comment]
不是啊，JD_WSCK=""这个我是写在config.sh

**Comment by Zy143L** [comment]
有没有一只可能 你前面没写 export

**Comment by Wangsc1** [comment]
### Zy143L脚本变量 ###
# wsck值
export JD_WSCK="xxx"
# 本地端口
export QL_PORT="5600"
# 直接更新
export WSKEY_DISCHECK="1"
# 自动禁用
export WSKEY_AUTO_DISABLE="1"
# 自动重试
export WSKEY_TRY_COUNT="3"

这个文件我备份的，直接恢复过去的

**Comment by Zy143L** [comment]
那可能是青龙毛病 变量没传递过去

**Comment by Wangsc1** [comment]
我就在环境变量里面新建了一个JD_COOKIE然后值随便填了一个，其他都没动

**Comment by Wangsc1** [comment]
好的，感谢
