### ISSUE TITLE
token失效时触发wskey转换报错

### ISSUE THREAD

**Issue by dmcslt** [Zy143L/wskey#242]
青龙版本2.9.7
```
5700端口检查通过
Token失效, 新登陆

Traceback (most recent call last):
  File "Zy143L_wskey_wskey.py", line 575, in <module>
    ql_id = check_id()  # 调用方法 [check_id] 并赋值 [ql_id]
  File "Zy143L_wskey_wskey.py", line 447, in check_id
    if '_id' in res['data'][0]:  # 判断 [_id]
KeyError: 'data'

## 更新任务状态失败(jwt expired)
```

**Comment by Zy143L** [comment]
更新一下青龙吧
