### ISSUE TITLE
2.10.13 今天刚刚拉的lasts版的青龙容器镜像 出现这个错误，不知道是啥问题

### ISSUE THREAD

**Issue by 2563411574** [Zy143L/wskey#256]
## 开始执行... 2022-10-31 02:24:12

# 当前总共 1 个 JD_COOKIE。

--------------------

5700端口检查通过
使用 _id 键值
HTTP Server Check OK
--------------------

Traceback (most recent call last):
  File "wskey.py", line 578, in <module>
    update()  # 调用方法 [update]
  File "wskey.py", line 383, in update
    up_ver = int(cloud_arg['update'])  # 云端参数取值 [int]
KeyError: 'update'

## 执行结束... 2022-10-31 02:24:13 耗时 1 秒

**Comment by Zy143L** [comment]
检查你的网络

**Comment by 2563411574** [comment]
> Owner

网络是正常的 但是不知道为啥还是这样

**Comment by Zy143L** [comment]
打开debug模式 从新执行

**Comment by 2563411574** [comment]
收到

**Comment by 2563411574** [comment]
# 开始执行... 2022-10-31 10:24:47

# 当前总共 0 个 JD_COOKIE。


DEBUG模式开启!


--------------------

5700端口检查通过
'twoFactorSecret'
Starting new HTTP connection (1): 127.0.0.1:5700
http://127.0.0.1:5700 "GET /api/user HTTP/1.1" 200 None
Starting new HTTP connection (1): 127.0.0.1:5700
http://127.0.0.1:5700 "GET /api/envs HTTP/1.1" 200 None
使用 _id 键值
Starting new HTTP connection (1): api.momoe.ml:80
http://api.momoe.ml:80 "GET / HTTP/1.1" 200 12
HTTP Server Check OK
--------------------

Starting new HTTP connection (1): api.momoe.ml:80
http://api.momoe.ml:80 "GET /api/check_api HTTP/1.1" 418 87
Traceback (most recent call last):
  File "wskey.py", line 578, in <module>
    update()  # 调用方法 [update]
  File "wskey.py", line 383, in update
    up_ver = int(cloud_arg['update'])  # 云端参数取值 [int]
KeyError: 'update'

**Comment by Zy143L** [comment]
稍等我看下

**Comment by Zy143L** [comment]
你外网IP多少 我后台查一下日志
