### ISSUE TITLE
KeyError: 'token'

### ISSUE THREAD

**Issue by bowie1127** [Zy143L/wskey#260]
请问问题在哪里，其他小软件用WSKEY都没问题的。

5700端口检查通过
Traceback (most recent call last):
  File "/ql/data/scripts/Zy143L_wskey/wskey.py", line 570, in <module>
    token = ql_login()  # 调用方法 [ql_login]  并赋值 [token]
            ^^^^^^^^^^
  File "/ql/data/scripts/Zy143L_wskey/wskey.py", line 198, in ql_login
    token = auth["token"]  # 提取 authkey
            ~~~~^^^^^^^^^
KeyError: 'token'

**Comment by Zy143L** [comment]
无后续问题 已关闭issues
