### ISSUE TITLE
注销wskey脚本有吗

### ISSUE THREAD

**Issue by a001980** [Zy143L/wskey#278]

**Comment by a001980** [comment]
> faker的脚本库应该有注册最简单的方法是直接修改密

用过了 没效果，才问问大佬。
[回复 Faker | iKun聚集地]
❗️注销所有 WSKEY, 错误!
Error: Cookie not in this host's domain. Cookie:plogin.m.jd.com Request:null
    at CookieJar.setCookie (/ql/data/scripts/node_modules/.pnpm/tough-cookie@4.0.0/node_modules/tough-cookie/lib/cookie.js:1133:15)
    at CookieJar.setCookie (/ql/data/scripts/node_modules/.pnpm/universalify@0.1.2/node_modules/universalify/index.js:5:67)
    at CookieJar.setCookieSync (/ql/data/scripts/node_modules/.pnpm/tough-cookie@4.0.0/node_modules/tough-cookie/lib/cookie.js:1642:17)
    at EventEmitter.<anonymous> (/ql/data/scripts/shufflewzc_faker2/jd_wskey_logout.js:230:4735)
    at EventEmitter.emit (node:events:513:28)
    at fns.<computed> (/ql/data/scripts/node_modules/.pnpm/got@11.5.1/node_modules/got/dist/source/core/utils/proxy-events.js:7:16)
    at PromisableRequest.emit (node:events:513:28)
    at PromisableRequest._onResponseBase (/ql/data/scripts/node_modules/.pnpm/got@11.5.1/node_modules/got/dist/source/core/index.js:813:22)
    at PromisableRequest._onResponse (/ql/data/scripts/node_modules/.pnpm/got@11.5.1/node_modules/got/dist/source/core/index.js:865:24)
    at ClientRequest.<anonymous> (/ql/data/scripts/node_modules/.pnpm/got@11.5.1/node_modules/got/dist/source/core/index.js:878:23)
