### ISSUE TITLE
青龙2.9.1-4版本使用出现错误

### ISSUE THREAD

**Issue by huiyi9420** [Zy143L/wskey#4]
## 开始执行... 2021-09-03 00:09:49

Verification passed
--------------------

pt_pin=账号打码 检索成功

Traceback (most recent call last):
  File "Zy143L_wskey_wskey.py", line 7, in <module>
    exec(zlib.decompress(base64.b64decode('

**Comment by Zy143L** [comment]
从新执行

**Comment by Zy143L** [comment]
如果还是有问题..检查青龙版本是不是2.9以上

**Comment by huiyi9420** [comment]
Rw==')))
  File "<string>", line 191, in <module>
  File "<string>", line 60, in check_ck
  File "/usr/lib/python3.8/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 456, in prepare_request
    p.prepare(
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 317, in prepare
    self.prepare_headers(headers)
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 451, in prepare_headers
    check_header_validity(header)
  File "/usr/lib/python3.8/site-packages/requests/utils.py", line 957, in check_header_validity
    raise InvalidHeader("Invalid return character or leading space in header: %s" % name)
requests.exceptions.InvalidHeader: Invalid return character or leading space in header: Cookie

## 执行结束... 2021-09-03 00:20:00 耗时 2 秒末尾这样的错误，重新执行也一样

**Comment by huiyi9420** [comment]
我重新拉取青龙吧，我怀疑我这个青龙有问题

**Comment by Zy143L** [comment]
有没有修改过青龙的端口 地址 或者加了两步验证等

**Comment by CyiceK** [comment]
@Zy143L  你应该标注这代码是Python3.9的函数(3.8跑不动的
上个版本我3.8跑不动，改了改才能跑

**Comment by Zy143L** [comment]
> @Zy143L 你应该标注这代码是Python3.9的函数(3.8跑不动的
> 上个版本我3.8跑不动，改了改才能跑

3.8跑的没问题啊 里面不存在3.9独有函数啊

**Comment by Zy143L** [comment]
![image](https://user-images.githubusercontent.com/21352718/131885903-83e7ddaa-f294-4d48-ab33-ca60f1931d83.png)

**Comment by CyiceK** [comment]
应该是他ql地址问题了，二步验证开了亲测没影响

**Comment by huiyi9420** [comment]
重装青龙已解决问题，感谢，请关闭这个问题

CyiceK ***@***.***>于2021年9月3日 周五01:26写道：
