### ISSUE TITLE
自动执行失败

### ISSUE THREAD

**Issue by cc123687** [Zy143L/wskey#61]
`Verification passed
--------------------

Traceback (most recent call last):
  File "Zy143L_wskey_wskey.py", line 420, in <module>
    sv, st, uuid, sign = get_sign()  # 获取认证参数
  File "Zy143L_wskey_wskey.py", line 240, in get_sign
    sign_list = json.loads(res.text)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`
每次都是这样，更新了也这样，手动没问题

**Comment by Zy143L** [comment]
最新的2021年9月16日的版本 更新一下

**Comment by Zy143L** [comment]
修改定时任务时间参数
