### ISSUE TITLE
获取云端参数超时

### ISSUE THREAD

**Issue by 2563411574** [Zy143L/wskey#74]
## 开始执行... 2021-09-25 18:10:00

--------------------

5700端口检查通过

获取云端参数超时, 正在重试!0

获取云端参数超时, 正在重试!1

获取云端参数超时, 正在重试!2
Traceback (most recent call last):
  File "Zy143L_wskey_wskey.py", line 409, in <module>
    update()
  File "Zy143L_wskey_wskey.py", line 261, in update
    up_ver = int(cloud_arg['update'])
TypeError: 'NoneType' object is not subscriptable

## 执行结束... 2021-09-25 18:11:01 耗时 61 秒

**Comment by Zy143L** [comment]
网络不稳定 建议重启网络 并修改定时任务时间
