### ISSUE TITLE
定时转换失败，已经修改过定时时间

### ISSUE THREAD

**Issue by imnono** [Zy143L/wskey#79]
如下，如果出现cookie到期，定时自动执行该脚本失败，这个时候需要手动执行下任务才可更新cookie
`5700端口检查通过

当前脚本版本: 916
--------------------

Verification passed
--------------------

Traceback (most recent call last):
  File "Zy143L_wskey_wskey.py", line 435, in <module>
    return_serch = serch_ck(wspin)  # 变量 pt_pin 搜索获取 key eid
  File "Zy143L_wskey_wskey.py", line 314, in serch_ck
    if len(res['data']) == 0:
KeyError: 'data'

**Comment by Zy143L** [comment]
已经修复 请更新脚本
